### PR TITLE
Fixed destroy() function, return mongo client argument, update README.md.

### PR DESCRIPTION
**Pull request by mrniceguy127**
The old
```js
this.db.close();
```
no longer works with node-mongodb-native v3.1.8: `TypeError: this.db.close is not a function`

Changed to:
```js
this.mongoClient.close();
```

### CODE REVIEW

**Comment by paulhobbel** [comment]
Thank you, will be published to npm asap
